import type { Business, Category, City } from "@/types/business";
import type { Listing } from "@/types/listing";

export const demoCities: City[] = [
  { id: "city-caracas", name: "Caracas", state: "Distrito Capital", slug: "caracas" },
  { id: "city-valencia", name: "Valencia", state: "Carabobo", slug: "valencia" },
  { id: "city-maracaibo", name: "Maracaibo", state: "Zulia", slug: "maracaibo" },
];

export const demoCategories: Category[] = [
  {
    id: "cat-tecnologia",
    name: "Tecnología",
    slug: "tecnologia",
    description: "Celulares, laptops, consolas y accesorios.",
  },
  {
    id: "cat-repuestos",
    name: "Repuestos",
    slug: "repuestos",
    description: "Autopartes y repuestos para carros.",
  },
  {
    id: "cat-hogar",
    name: "Hogar",
    slug: "hogar",
    description: "Electrodomésticos y soluciones del hogar.",
  },
];

const businesses: Business[] = [
  {
    id: "biz-tech-caracas-store",
    name: "Tech Caracas Store",
    slug: "tech-caracas-store",
    description: "Tienda de tecnología con entrega en Caracas y atención por WhatsApp.",
    whatsapp_number: "584121112233",
    instagram_url: "https://instagram.com/techcaracasstore",
    website_url: null,
    address_text: "Chacao, Caracas",
    delivery_available: true,
    pickup_available: true,
    payment_mobile: true,
    zelle: true,
    usdt: false,
    cash_usd: true,
    verified: true,
    active: true,
    city_id: "city-caracas",
    category_id: "cat-tecnologia",
    city: demoCities[0],
    category: demoCategories[0],
  },
  {
    id: "biz-garage-valencia",
    name: "Garage Valencia Parts",
    slug: "garage-valencia-parts",
    description: "Repuestos rápidos para Toyota, Chevrolet y Ford en Valencia.",
    whatsapp_number: "584142223344",
    instagram_url: "https://instagram.com/garagevalenciaparts",
    website_url: null,
    address_text: "Naguanagua, Valencia",
    delivery_available: false,
    pickup_available: true,
    payment_mobile: true,
    zelle: false,
    usdt: false,
    cash_usd: true,
    verified: true,
    active: true,
    city_id: "city-valencia",
    category_id: "cat-repuestos",
    city: demoCities[1],
    category: demoCategories[1],
  },
  {
    id: "biz-casa-smart-mcbo",
    name: "Casa Smart Maracaibo",
    slug: "casa-smart-maracaibo",
    description: "Línea blanca, freidoras de aire y pequeños electrodomésticos.",
    whatsapp_number: "584244556677",
    instagram_url: "https://instagram.com/casasmartmcbo",
    website_url: null,
    address_text: "Maracaibo, Zulia",
    delivery_available: true,
    pickup_available: true,
    payment_mobile: true,
    zelle: true,
    usdt: true,
    cash_usd: true,
    verified: false,
    active: true,
    city_id: "city-maracaibo",
    category_id: "cat-hogar",
    city: demoCities[2],
    category: demoCategories[2],
  },
];

export const demoListings: Listing[] = [
  {
    id: "list-iphone-13",
    business_id: "biz-tech-caracas-store",
    title: "iPhone 13 128GB",
    slug: "iphone-13-128gb-tech-caracas-store",
    description: "Disponible con entrega en Caracas y retiro el mismo día.",
    city_id: "city-caracas",
    category_id: "cat-tecnologia",
    price_from: 650,
    currency: "USD",
    in_stock: true,
    source_type: "manual",
    source_url: "https://instagram.com/techcaracasstore",
    featured: true,
    active: true,
    business: businesses[0],
    city: demoCities[0],
    category: demoCategories[0],
  },
  {
    id: "list-lenovo-ideapad",
    business_id: "biz-tech-caracas-store",
    title: "Laptop Lenovo IdeaPad 15",
    slug: "laptop-lenovo-ideapad-15-tech-caracas-store",
    description: "Ideal para estudio y trabajo remoto.",
    city_id: "city-caracas",
    category_id: "cat-tecnologia",
    price_from: 540,
    currency: "USD",
    in_stock: true,
    source_type: "manual",
    source_url: "https://instagram.com/techcaracasstore",
    featured: false,
    active: true,
    business: businesses[0],
    city: demoCities[0],
    category: demoCategories[0],
  },
  {
    id: "list-toyota-corolla-bomba",
    business_id: "biz-garage-valencia",
    title: "Bomba de gasolina Toyota Corolla 2009-2013",
    slug: "bomba-gasolina-toyota-corolla-garage-valencia",
    description: "Repuesto nuevo con entrega contra pedido en Valencia.",
    city_id: "city-valencia",
    category_id: "cat-repuestos",
    price_from: 85,
    currency: "USD",
    in_stock: true,
    source_type: "manual",
    source_url: "https://instagram.com/garagevalenciaparts",
    featured: true,
    active: true,
    business: businesses[1],
    city: demoCities[1],
    category: demoCategories[1],
  },
  {
    id: "list-airfryer-oster",
    business_id: "biz-casa-smart-mcbo",
    title: "Freidora de aire Oster 4L",
    slug: "freidora-aire-oster-casa-smart-maracaibo",
    description: "Con delivery en Maracaibo y pago móvil.",
    city_id: "city-maracaibo",
    category_id: "cat-hogar",
    price_from: 110,
    currency: "USD",
    in_stock: true,
    source_type: "manual",
    source_url: "https://instagram.com/casasmartmcbo",
    featured: false,
    active: true,
    business: businesses[2],
    city: demoCities[2],
    category: demoCategories[2],
  },
];

export function getDemoBusinesses() {
  return businesses;
}
